models/__init__.py
from peewee import SqliteDatabase
from .db import db
from .contents import Contents

Models = [Contents]

def initialize_database():
    db.connect()
    db.create_tables(Models, safe=True)
    db.close()

models/contents.py
from peewee import Model, CharField, IntegerField, DateTimeField
from .db import db

class Contents(Model):
    id = IntegerField(primary_key=True)
    created_at = DateTimeField()

    #名前
    name = CharField()

    #値段
    price = IntegerField()

    #入った日
    entry = DateTimeField()

    #支払い日
    payment_date = DateTimeField()

    class Meta:
        database = db

models/db.py
from peewee import SqliteDatabase

# データベース接続の定義
db = SqliteDatabase('contents.db')

app.py
from flask import Flask, render_template
from models import initialize_database
from models import Contents
from routes import blueprints
from playhouse.shortcuts import model_to_dict
app = Flask(__name__)

initialize_database()

for blueprint in blueprints:
    app.register_blueprint(blueprint)

@app.route('/')
def index():
    # ここでバックのデータ処理
    # データベースからContentsクラス(サブスクのデータ)を取得  
    contents = Contents.select()
    # contentsを辞書型に変換し、リストに格納
    contents_dict = [model_to_dict(content) for content in contents]
    # 金額が高い順にソートする
    # reverse=Trueで値段が高い順、Falseで安い順にソート
    contents_dict.sort(key=lambda x: x['price'], reverse=True)
    # print(contents_dict)
    # index.htmlにcontents_dicとして渡す
    return render_template('index.html', contents_dict=contents_dict)
    
if __name__ == '__main__':
    app.run(port=8080, debug=True)

routes/__init__.py
from .content import content_bp
from .add import add_bp
from .edit import edit_bp
from .delete import delete_bp

blueprints = [content_bp, add_bp, edit_bp, delete_bp]

routes/add.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Contents
from datetime import date

add_bp = Blueprint('add', __name__, url_prefix='/add')

#データ追加ページの処理を追加
@add_bp.route('/', methods=['GET', 'POST'])
def add():
    #POSTメソッドでリクエストがあった場合の処理
    if request.method == 'POST':
        created_at = date.today()
        name = request.form['name']
        price = int(request.form['price'])
        entry = date.fromisoformat(request.form['entry'])
        payment_date = date.fromisoformat(request.form['payment_date'])
        Contents.create(created_at=created_at, name=name, price=price, entry=entry, payment_date=payment_date)

        return redirect(url_for('index'))

    #入力するだけなのでテンプレートに送らない
    return render_template('add.html')

routes/content.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Contents

content_bp = Blueprint('content', __name__, url_prefix='/content')

@content_bp.route('/<int:content_id>')
def content(content_id):
    content = Contents.get_or_none(Contents.id == content_id)
    contents = Contents.select()
    return render_template('content.html',content=content, contents=contents)

routes/delete.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Contents
from peewee import DoesNotExist

delete_bp = Blueprint('delete', __name__)

@delete_bp.route('/content/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    try:
        # 指定された ID のデータを取得
        content = Contents.get(Contents.id == id)
    except DoesNotExist:
        # データが存在しない場合はホームにリダイレクト
        return redirect(url_for('index'))

    if request.method == 'POST':
        # 削除処理
        content.delete_instance()
        return redirect(url_for('index'))  # 削除後にホーム画面にリダイレクト

    # GET メソッドの場合、削除確認ページを表示
    return render_template('delete.html', content=content)

routes/edit.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Contents
from peewee import DoesNotExist
from datetime import date

edit_bp = Blueprint('edit', __name__)

@edit_bp.route('/content/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    
    content = Contents.get(Contents.id == id)
    if not content:
        return redirect(url_for('index'))  # データが見つからなかった場合のリダイレクト

    if request.method == 'POST':
        content.name = request.form['name']
        content.price = int(request.form['price'])
        content.entry = date.fromisoformat(request.form['entry'])
        content.payment_date = date.fromisoformat(request.form['payment_date'])
        content.save()
        return redirect(url_for('index'))  # 保存後のリダイレクト

    return render_template('edit.html', content=content)

templates/add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <title>サブスク追加</title>
  </head>
  <body class="inputContainer">
    <h1>サブスク追加</h1>
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('index') }}">HOME</a></li>
      <li class="breadcrumb-item active">追加</li>
    </ul>
    <form action="" method="post">
      <!-- サービス名入力欄 -->
      <div class="col-12">
        <label for="service" class="form-label">サービス名 </label>
        <input type="service" class="form-control" id="service" placeholder="Amazon Prime" name="name" required>
        <div class="invalid-feedback">
          サービス名を入力してください
        </div>
      </div>
      <!-- 値段入力欄 -->
      <div class="col-12">
        <label for="price" class="form-label">値段 </label>
        <input type="price" class="form-control" id="price" placeholder="600" name="price" required>
        <div class="invalid-feedback">
          値段を入力してください
        </div>
      </div>
      <!-- 登録日入力欄 -->
      <div class="col-12">
        <label for="entry" class="form-label">登録日 </label>
        <input type="date" class="form-control" id="entry" placeholder="20XX-XX-XX" name="entry" required>
        <div class="invalid-feedback">
          登録日を入力してください
        </div>
      </div>
      <!-- 支払日入力欄 -->
      <div class="col-12">
        <label for="payment_date" class="form-label">支払日 </label>
        <input type="date" class="form-control" id="payment_date" name="payment_date" required>
        <div class="invalid-feedback">
          支払日を入力してください
        </div>
      <br />
      <!-- 登録ボタン -->
      <button class="btn btn-primary rounded-pill px-3" type="submit"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">追加</font></font></button>
      </button>

      <li><a href="{{ url_for('index') }}">トップに戻る</a></li>
    </form>
  </body>
</html>

templates/content.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="d-flex">
      <!-- Main -->
      <div class="p-3 flex-grow-1">
        <div class="ms-auto d-flex justify-content-end">
          <a
            type="button"
            class="btn btn-outline-primary me-2"
            href="{{ url_for('edit.edit', id=content.id) }}"
          >
            編集
          </a>
          <a
            type="button"
            class="btn btn-outline-danger me-2"
            href="{{ url_for('delete.delete', id=content.id) }}"
          >
            削除
          </a>
        </div>
        <div class="p-3">
          <h1>{{ content.name }}</h1>
          <div
            class="p-3 alert alert-warning"
            style="width: 200px"
            role="alert"
          >
            <div class="item-row">
              <span class="label">値段:</span>
              <span class="value">{{ content.price }}円</span>
            </div>
            <div class="item-row">
              <span class="label">登録日:</span>
              <span class="value"
                >{{ content.entry.strftime('%Y/%m/%d') }}</span
              >
            </div>
            <div class="item-row">
              <span class="label">支払日:</span>
              <span class="value"
                >{{ content.payment_date.strftime('%Y/%m/%d') }}</span
              >
            </div>
          </div>
          <div>
            <a type="button" class="btn me-2" href="{{ url_for('index') }}">
              ←top
            </a>
          </div>
        </div>
      </div>

      <!-- Sidebar -->
      <div
        class="flex-shrink-0 p-3 border-start"
        style="width: 160px; height: 100vh; background-color: #f8f9fa"
      >
        <a
          class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom"
          >一覧</a
        >
        <ul class="list-unstyled">
          <div class="collapse show" id="home-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
              {% for item in contents %}
              <li>
                <a
                  class="dropdown-item rounded-2 active"
                  onmouseover="this.style.backgroundColor='#d3d3d3'; this.style.color='#000';"
                  onmouseout="this.style.backgroundColor=''; this.style.color='';"
                  href="{{ url_for('content.content', content_id=item.id) }}"
                >
                  {{ item.name }}
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </ul>
      </div>
    </div>
  </body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <title>削除ページ</title>
</head>
<body class="inputContainer">
    <h1>削除ページ</h1>
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('index') }}">HOME</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('content.content', content_id=content.id) }}">詳細</a></li>
        <li class="breadcrumb-item active">削除確認</li>
    </ul>

    <div class="alert alert-warning" role="alert">
        <p>以下の内容を削除しますか？</p>
        <p><strong>サブスク名:</strong> {{ content.name }}</p>
        <p><strong>値段:</strong> {{ content.price }}</p>
        <p><strong>登録日:</strong> {{ content.entry.strftime('%Y/%m/%d') }}</p>
        <p><strong>支払日:</strong> {{ content.payment_date.strftime('%Y/%m/%d') }}</p>
    </div>

    <form action="{{ url_for('delete.delete', id=content.id) }}" method="post">
        <button type="submit" class="btn btn-danger">削除</button>
        <a href="{{ url_for('index') }}" class="btn btn-secondary">キャンセル</a>
    </form>

    <script>
        // 削除ボタンのクリックイベントを監視
        document.getElementById('deleteButton').addEventListener('click', function(event) {
            // 確認ダイアログを表示
            if (!confirm('本当に削除しますか？')) {
                // ユーザーが「キャンセル」を選んだ場合、フォーム送信を停止
                event.preventDefault();
            }
        });
    </script>
</body>
</html>

templates/edit.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <title>サブスク編集</title>
  </head>
  <body class="inputContainer">
    <h1>サブスク編集</h1>
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('index') }}">HOME</a></li>
      <li class="breadcrumb-item"><a href="{{ url_for('content.content', content_id=content.id) }}">詳細</a></li>
      <li class="breadcrumb-item active">編集</li>
  </ul>
      <!-- サービス名入力欄 -->
      <form action="{{ url_for('edit.edit', id=content.id) }}" method="post">
        <label for="service" class="form-label">サービス名 </label>
        <input type="service" name="name" value="{{ content.name }}"   class="form-control" id="service" placeholder="Amazon Prime" required>
        <div class="invalid-feedback">
          サービス名を入力してください
        </div>
        <!-- 値段入力欄 -->
        <div class="col-12">
          <label for="price" class="form-label">値段 </label>
            <input type="text" step="1" name="price" value="{{ content.price }}"  class="form-control" id="price" placeholder="600" required>
            <div class="invalid-feedback">
              値段を入力してください
            </div>
          </div>
        <!-- 登録日入力欄 -->
        <div class="col-12">
          <label for="entry" class="form-label">登録日 </label>
            <input type="date" name="entry" value="{{ content.entry.strftime('%Y-%m-%d') }}" class="form-control" id="entry" required>
            <div class="invalid-feedback">
              登録日を入力してください
            </div>
          </div>
        <!-- 支払日入力欄 --> 
        <div class="col-12">
          <label for="payment_date" class="form-label">支払日 </label>
            <input type="date" name="payment_date" value="{{ content.payment_date.strftime('%Y-%m-%d') }}" class="form-control" id="payment_date" required >
            <div class="invalid-feedback">
              支払日を入力してください
            </div>
        
        <br />
        <!-- 登録ボタン -->
        <button class="btn btn-primary rounded-pill px-3" type="submit"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">保存</font></font></button>

        <li><a href="{{ url_for('index') }}">トップに戻る</a></li>
    </form>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>サブスク管理アプリ</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

</head>

<header>
    <a href="" class="title">サブスク管理</a>
    <ul>
        <li><a href="add" class="menu-item">サブスクの登録</a></li>
    </ul>

    <div id="toggle-container">
        <button id="month-button" class="toggle-button">月</button>
        <button id="year-button" class="toggle-button">年</button>
    </div>
</header>

<body>

    <div class="indexContainer">

        <div id="no-subscription" class="hidden">
            Not subscription.
        </div>
    
        <div id="graphs-container">
            <div id="totalchart-container">
                <canvas id="totalchart" width="600" height="600"></canvas>
            </div>
            <div id="individual-container">
                <canvas id="individualchart" width="600" height="600"></canvas>
            </div>
        </div>
    </div>
    <script>
        <!--index.htmlからindex.jsにcontents_dictとして渡す-->
        window.contents_dict = {{ contents_dict|tojson|safe }};
        console.log("Contents dict initialized:", window.contents_dict);
    </script>
    <script src="static/index.js"></script>
</body>
</html>